/*

 SNAKE_BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 20
   Tile set      : D:\Gameboy Development\sprites\snake_game\snake_bg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __snake_bg_h_INCLUDE
#define __snake_bg_h_INCLUDE

#define snake_bg_mapWidth 20
#define snake_bg_mapHeight 20
#define snake_bg_mapBank 0

extern const unsigned char snake_bg_map[];

#endif

/* End of SNAKE_BG.H */
